In [1]:
import numpy as np


In [3]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
# Second method we used to display the row
for cell in a.flatten():
    print(cell)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
#Nditer Function in C order
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [7]:
#Nditer Function in Fortan order
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [10]:
#External loop
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)


[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [11]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [12]:
a


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [13]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [16]:
for x,y in np.nditer([a,b]):
    print(x,y)
                

IndentationError: expected an indented block after 'for' statement on line 1 (2190050416.py, line 2)